# Generated by Django 6.0.8 on 2026-09-02 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo_produtos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='imagen',
            field=models.CharField(default='default.png', max_length=200),
        ),
    ]
